import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { CreditCard, Lock, ShieldCheck, Sparkles, Tag } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { useToast } from '@/components/ui/Toast';
import { ApiError } from '@/services/api/client';
import { createCheckoutOrder, initiateStripe, quoteCheckout, type CheckoutQuote } from '@/services/api/checkout';
import { useAuth } from '@/services/auth-context';
import { metaTrackingContext, trackMetaInitiateCheckout } from '@/services/metaTracking';
import { formatMoney } from '@/lib/money';

export default function Checkout(){
 const [params]=useSearchParams(); const toast=useToast(); const {user,initializing}=useAuth();
 const [coupon,setCoupon]=useState(''); const [appliedCoupon,setAppliedCoupon]=useState(''); const [loading,setLoading]=useState(false); const [quoteLoading,setQuoteLoading]=useState(true); const [quote,setQuote]=useState<CheckoutQuote|null>(null); const [quoteError,setQuoteError]=useState(''); const [customer,setCustomer]=useState({name:'',email:''});
 const productId=Number(params.get('product_id')||0), bundleId=Number(params.get('bundle_id')||0), landingPageSlug=params.get('landing_page_slug')||params.get('lp')||'', offerKey=params.get('offer_key')||params.get('offer')||'';
 const offerPayload=useMemo(()=>landingPageSlug?{landing_page_slug:landingPageSlug,offer_key:offerKey||'single'}:bundleId?{bundle_id:bundleId}:{product_id:productId},[bundleId,landingPageSlug,offerKey,productId]);
 useEffect(()=>{if(!initializing&&user)setCustomer(p=>({name:p.name||user.name,email:p.email||user.email}));},[initializing,user]);
 useEffect(()=>{setQuoteLoading(true);quoteCheckout(offerPayload).then(q=>{setQuote(q);setQuoteError('')}).catch(()=>setQuoteError('This offer is currently unavailable.')).finally(()=>setQuoteLoading(false));},[offerPayload]);
 useEffect(()=>{if(quote)void trackMetaInitiateCheckout({contentIds:[`${quote.type}:${quote.id}`],contentName:quote.title,contentType:'product',value:quote.total,currency:quote.currency,numItems:1});},[quote]);
 async function applyCoupon(){try{const q=await quoteCheckout({...offerPayload,coupon_code:coupon.trim()});setQuote(q);setAppliedCoupon(q.couponCode||coupon.trim().toUpperCase());toast({type:'success',title:'Coupon applied'});}catch(e){toast({type:'error',title:'Coupon not valid',message:e instanceof ApiError?e.message:'Check the code and try again.'});}}
 async function pay(){if(!quote||!customer.name||!customer.email)return toast({type:'error',title:'Name and email required'}); setLoading(true); try{const order=await createCheckoutOrder({...offerPayload,coupon_code:appliedCoupon||undefined,customer_name:customer.name,customer_email:customer.email,payment_method:'stripe',tracking_context:metaTrackingContext()}); if(order.guest_access_token)sessionStorage.setItem(`guest_access_token:${order.order_number}`,order.guest_access_token); const session=await initiateStripe(order.order_number); window.location.assign(session.checkout_url);}catch(e){toast({type:'error',title:'Checkout failed',message:e instanceof ApiError?e.message:'Please try again.'});setLoading(false);}}
 const total=quote?.total||0;
 return <div className="container-page py-10 lg:py-16"><div className="mx-auto grid max-w-5xl gap-8 lg:grid-cols-[1fr_390px]">
  <div><div className="mb-8"><span className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-brand-700"><Sparkles className="h-4 w-4"/>A lighter checkout</span><h1 className="mt-3 font-display text-3xl font-semibold text-ink-900">Your next reset starts here.</h1><p className="mt-2 max-w-xl text-ink-500">Instant digital access after secure payment. No account required.</p></div>
  <section className="card-surface p-6"><h2 className="font-semibold text-ink-900">Contact information</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Input label="Full name" value={customer.name} onChange={e=>setCustomer(p=>({...p,name:e.target.value}))} required/><Input label="Email" type="email" value={customer.email} onChange={e=>setCustomer(p=>({...p,email:e.target.value}))} required/></div><p className="mt-3 text-xs text-ink-400">We’ll send your receipt and secure access link here.</p></section>
  <section className="card-surface mt-5 p-6"><h2 className="font-semibold text-ink-900">Payment</h2><div className="mt-4 flex items-center gap-4 rounded-2xl border border-brand-200 bg-brand-50 p-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-brand-700 text-white"><CreditCard className="h-5 w-5"/></div><div><p className="font-semibold text-ink-900">Secure card checkout with Stripe</p><p className="text-sm text-ink-500">You’ll continue to Stripe to complete payment.</p></div></div><div className="mt-4 flex items-center gap-2 text-xs text-ink-400"><ShieldCheck className="h-4 w-4"/>EverydayLighter does not store your card details.</div></section></div>
  <aside className="lg:sticky lg:top-24 lg:self-start"><div className="card-surface overflow-hidden"><div className="border-b border-ink-100 p-5"><p className="text-sm font-semibold">Order summary</p></div><div className="p-5">{quoteLoading?<p className="text-sm text-ink-500">Loading offer…</p>:quoteError?<p className="text-sm text-danger-600">{quoteError}</p>:quote&&<><p className="font-display text-xl font-semibold">{quote.title}</p><div className="mt-5 flex gap-2"><Input placeholder="Coupon code" value={coupon} onChange={e=>setCoupon(e.target.value)} leftIcon={<Tag className="h-4 w-4"/>}/><Button variant="outline" onClick={applyCoupon}>Apply</Button></div><div className="mt-6 space-y-2 border-t border-ink-100 pt-4 text-sm"><div className="flex justify-between"><span className="text-ink-500">Subtotal</span><span>{formatMoney(quote.subtotal,quote.currency)}</span></div>{quote.discount>0&&<div className="flex justify-between text-success-700"><span>Discount</span><span>-{formatMoney(quote.discount,quote.currency)}</span></div>}<div className="flex justify-between border-t border-ink-100 pt-3 text-base font-bold"><span>Total</span><span>{formatMoney(total,quote.currency)}</span></div></div></>}<Button className="mt-5 w-full" size="lg" loading={loading} disabled={!quote||quoteLoading||!!quoteError} onClick={pay}><Lock className="h-4 w-4"/>Pay {quote?formatMoney(total,quote.currency):''}</Button><p className="mt-3 text-center text-[11px] leading-5 text-ink-400">By continuing, you agree to our Terms, Privacy Policy and digital-product Refund Policy.</p></div></div></aside>
 </div></div>;
}
