import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { BookOpen, CheckCircle2, Clock3, Download, Mail, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { apiRequest, minorToDisplay } from '@/services/api/client';
import { verifyStripeSession } from '@/services/api/checkout';
import { formatMoney } from '@/lib/money';
import { trackMetaPurchase } from '@/services/metaTracking';

type Receipt={order_number:string;payment_status:string;total_minor:number;currency:string;items:{product_name:string;total_minor:number}[];meta?:{purchase_event_id:string;content_ids:string[];content_type:string;num_items:number;value:number;currency:string}};
export default function PurchaseSuccess(){const [params]=useSearchParams();const [receipt,setReceipt]=useState<Receipt|null>(null);const [downloads,setDownloads]=useState<{download_url:string;name:string}[]>([]);const [message,setMessage]=useState('Confirming your payment…');const order=params.get('order')||'';const sessionId=params.get('session_id')||'';const token=order?sessionStorage.getItem(`guest_access_token:${order}`)||'':'';
 useEffect(()=>{if(!order||!sessionId){setMessage('Your payment return link is incomplete.');return;} verifyStripeSession(sessionId).then(async()=>{const suffix=token?`?guest_access_token=${encodeURIComponent(token)}`:'';const r=await apiRequest<{data:Receipt}>(`/checkout/orders/${order}/receipt${suffix}`);setReceipt(r.data);setMessage('');if(token){const g=await apiRequest<{data:{downloads:{download_url:string;name:string}[]}}>(`/guest/orders/${order}${suffix}`);setDownloads(g.data.downloads||[]);}}).catch(()=>setMessage('We are still confirming the payment. Refresh in a moment or check your email.'));},[order,sessionId,token]);
 useEffect(()=>{if(receipt?.payment_status==='paid'&&receipt.meta?.purchase_event_id)void trackMetaPurchase({eventId:receipt.meta.purchase_event_id,contentIds:receipt.meta.content_ids,contentType:receipt.meta.content_type,value:receipt.meta.value,currency:receipt.meta.currency,numItems:receipt.meta.num_items});},[receipt]);
 const paid=receipt?.payment_status==='paid';return <div className="container-page py-16"><div className="mx-auto max-w-2xl text-center"><div className={`mx-auto grid h-16 w-16 place-items-center rounded-full ${paid?'bg-success-100 text-success-700':'bg-brand-100 text-brand-700'}`}>{paid?<CheckCircle2 className="h-9 w-9"/>:<Clock3 className="h-8 w-8"/>}</div><h1 className="mt-5 font-display text-3xl font-semibold">{paid?'Your purchase is ready':'Almost there'}</h1><p className="mt-2 text-ink-500">{paid?'A little less to carry, starting now.':message}</p>{receipt&&<div className="card-surface mt-8 p-6 text-left"><p className="text-xs font-bold uppercase tracking-widest text-brand-700">Order {receipt.order_number}</p><h2 className="mt-2 font-display text-2xl font-semibold">{receipt.items[0]?.product_name}</h2><p className="mt-2 font-semibold">{formatMoney(minorToDisplay(receipt.total_minor)||0,receipt.currency)}</p><div className="mt-6 flex flex-col gap-3 sm:flex-row">{downloads[0]&&<Button className="flex-1" onClick={()=>window.location.assign(downloads[0].download_url)}><Download className="h-4 w-4"/>Download now</Button>}<Link className="flex-1" to="/account/library"><Button variant="outline" className="w-full"><BookOpen className="h-4 w-4"/>My library</Button></Link></div></div>}<div className="mt-6 flex items-center justify-center gap-2 text-sm text-ink-400"><Mail className="h-4 w-4"/>A receipt and access link are sent by email.</div><div className="mt-2 flex items-center justify-center gap-2 text-xs text-ink-400"><ShieldCheck className="h-4 w-4"/>Secure fulfillment by EverydayLighter.</div></div></div>}
