import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, Check, Heart, Sparkles } from 'lucide-react';
import { getHomeCatalog, type ApiProduct } from '@/services/api/catalog';
import { formatMoney } from '@/lib/money';

export default function Home(){const [products,setProducts]=useState<ApiProduct[]>([]);useEffect(()=>{getHomeCatalog().then(d=>setProducts(d.featured.length?d.featured:d.newArrivals)).catch(()=>undefined)},[]);return <>
<section className="overflow-hidden bg-[#fffaf5]"><div className="container-page grid min-h-[620px] items-center gap-12 py-16 lg:grid-cols-[1.1fr_.9fr]"><div><div className="inline-flex items-center gap-2 rounded-full border border-brand-200 bg-white px-4 py-2 text-xs font-semibold uppercase tracking-[.15em] text-brand-800"><Sparkles className="h-4 w-4"/>Practical tools for real life</div><h1 className="mt-7 max-w-3xl font-display text-5xl font-semibold leading-[1.04] tracking-tight text-ink-900 sm:text-6xl">Make everyday life feel <em className="font-normal text-brand-700">lighter.</em></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-ink-500">Research-informed guides, workbooks, and simple systems that help you carry less, decide faster, and make room for yourself again.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/products" className="inline-flex items-center gap-2 rounded-full bg-brand-800 px-6 py-3.5 font-semibold text-white">Explore the collection <ArrowRight className="h-4 w-4"/></Link><a href="#why" className="inline-flex items-center rounded-full border border-ink-200 bg-white px-6 py-3.5 font-semibold text-ink-700">Why EverydayLighter</a></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-2 text-sm text-ink-500">{['Instant digital access','Secure Stripe checkout','Practical, not preachy'].map(x=><span key={x} className="flex items-center gap-2"><Check className="h-4 w-4 text-success-600"/>{x}</span>)}</div></div><div className="relative mx-auto w-full max-w-md"><div className="absolute -left-8 top-12 h-56 w-56 rounded-full bg-[#eadfd7] blur-3xl"/><div className="relative rounded-[2rem] border border-brand-100 bg-white p-7 shadow-[0_30px_80px_rgba(74,43,55,.14)]"><div className="rounded-[1.5rem] bg-gradient-to-br from-brand-900 via-brand-800 to-[#7b5563] p-8 text-white"><p className="text-xs uppercase tracking-[.24em] text-white/65">Featured reset</p><h2 className="mt-5 font-display text-4xl font-semibold leading-tight">The Mental Load Reset</h2><p className="mt-4 leading-7 text-white/80">Stop carrying the whole family in your head.</p><div className="mt-10 h-px bg-white/20"/><p className="mt-5 text-sm text-white/70">A practical 30-day system for overwhelmed women and moms.</p></div></div></div></div></section>
<section id="why" className="container-page py-20"><div className="mx-auto max-w-2xl text-center"><span className="text-xs font-bold uppercase tracking-[.18em] text-brand-700">Designed for the life you actually have</span><h2 className="mt-3 font-display text-4xl font-semibold">Less pressure. Better systems. More room.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[[Heart,'Feel understood','Tools built around the invisible work that fills your head.'],[BookOpen,'Use it today','Clear steps, worksheets, scripts and systems — not vague inspiration.'],[Sparkles,'Keep what works','Small changes designed to reduce daily friction and decision fatigue.']].map(([Icon,t,d]:any)=><div key={t} className="rounded-3xl border border-ink-100 bg-white p-7"><div className="grid h-11 w-11 place-items-center rounded-full bg-brand-50 text-brand-700"><Icon className="h-5 w-5"/></div><h3 className="mt-5 font-display text-2xl font-semibold">{t}</h3><p className="mt-2 leading-7 text-ink-500">{d}</p></div>)}</div></section>
<section className="bg-[#f7f1eb] py-20"><div className="container-page"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-700">The EverydayLighter shelf</p><h2 className="mt-2 font-display text-4xl font-semibold">Start where life feels heaviest.</h2></div><Link to="/products" className="hidden items-center gap-2 text-sm font-semibold text-brand-800 sm:flex">View all <ArrowRight className="h-4 w-4"/></Link></div><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.slice(0,3).map(p=><Link key={p.id} to={`/p/${p.slug}`} className="group overflow-hidden rounded-3xl border border-ink-100 bg-white"><div className="aspect-[4/3] overflow-hidden bg-brand-50">{p.cover?<img src={p.cover} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]"/>:<div className="grid h-full place-items-center text-brand-700"><BookOpen className="h-12 w-12"/></div>}</div><div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-brand-700">{p.category}</p><h3 className="mt-2 font-display text-2xl font-semibold">{p.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-ink-500">{p.shortDescription}</p><p className="mt-4 font-semibold">{formatMoney(p.salePrice??p.regularPrice,p.currency)}</p></div></Link>)}</div></div></section>
</>}
